#!/bin/bash
#
#  curl commands to reload the data from the previous tutorial
#
#

set -e

echo -e "⏳ Loading context data in \033[1mNGSI-LD\033[0m format"
echo -e "    - all entity data models are defined referencing the"
echo -e "      \033[1m"${TUTORIAL_DATA_MODELS_CONTEXT}"\033[0m JSON-LD context"

#
# Create four Farm Entities in various locations across Berlin
#
curl -s -o /dev/null -X POST 'http://'"${CONTEXT_BROKER}"'/ngsi-ld/v1/entityOperations/upsert' \
-H 'Content-Type: application/json' \
-H 'Link: <'"${TUTORIAL_DATA_MODELS_CONTEXT}"'>; rel="http://www.w3.org/ns/json-ld#context"; type="application/ld+json"' \
-H 'Accept: application/ld+json' \
--data-raw '[
  {
    "id": "urn:ngsi-ld:Person:Ole",
    "type": "Person",
    "address": {
      "@type": "PostalAddress",
      "addressLocality": "Berlin",
      "addressRegion": "Berlin",
      "postalCode": "14199",
      "streetAddress": "Detmolder Str. 10"
    },
    "telephone": { "type": "Property", "value": "0049 1522 99999999"},
    "email": {"type": "Property", "value": "ole-lahm@xyz.foo"},
    "name": {"type": "Property", "value": "Ole Lahm"}
  },
  {
    "id": "urn:ngsi-ld:Person:Torsten",
    "type": "Person",
    "address": {
      "@type": "PostalAddress",
      "addressLocality": "Berlin",
      "addressRegion": "Berlin",
      "postalCode": "10997",
      "streetAddress": "Eisenbahnstraße 42/43"
    },
    "telephone": { "type": "Property", "value": "0049 1533 8888888"},
    "email": {"type": "Property", "value": "torsten-kühl@xyz.foo"},
    "name": {"type": "Property", "value": "Torsten Kühl"}
  },
  {
    "id": "urn:ngsi-ld:Person:Frank",
    "type": "Person",
    "address": {
      "@type": "PostalAddress",
      "addressLocality": "Berlin",
      "addressRegion": "Berlin",
      "postalCode": "10178",
      "streetAddress": "Panoramastraße 1A"
    },
    "telephone": { "type": "Property", "value": "0049 1544 7777777"},
    "email": {"type": "Property", "value": "frank-regio@xyz.foo"},
    "name": {"type": "Property", "value": "Frank Regio"}
  },
  {
    "id": "urn:ngsi-ld:Person:Lothar",
    "type": "Person",
    "address": {
      "@type": "PostalAddress",
      "addressLocality": "Berlin",
      "addressRegion": "Berlin",
      "postalCode": "10117",
      "streetAddress": "Pariser Platz"
    },
    "telephone": { "type": "Property", "value": "0049 1555 6666666"},
    "email": {"type": "Property", "value": "mailto:lothar-lammich@xyz.foo"},
    "name": {"type": "Property", "value": "Lothar Lammich"}
  },
  {
    "id": "urn:ngsi-ld:Person:Lothar",
    "type": "Person",
    "address": {
      "@type": "PostalAddress",
      "addressLocality": "Berlin",
      "addressRegion": "Berlin",
      "postalCode": "10117",
      "streetAddress": "Pariser Platz"
    },
    "telephone": { "type": "Property", "value": "0049 1555 6666666"},
    "email": {"type": "Property", "value": "mailto:lothar-lammich@xyz.foo"},
    "name": {"type": "Property", "value": "Lothar Lammich"}
  }
]'

echo -e " \033[1;32mdone\033[0m"
