#!/bin/bash
#
#  http commands to management of application roles
#
#

set -e

echo -e "⏳ Obtaining the X-Subject-Token for admin user: Alice"

#
# Get admin token
#
TOKEN=$(http -h POST http://localhost:3005/v1/auth/tokens \
  name=alice-the-admin@test.com \
  password=test | grep 'X-Subject-Token' | awk '{print $2}')

echo -e "          ... Token: $TOKEN"
export TOKEN


#
# Create new application
#
echo
echo -e "⏳ Creating a new application into IdM"

APP=$(printf '{
  "application": {
    "name": "Personal Data Mgmt. Application",
    "description": "FIWARE Application protected by OAuth2 for managing Personal Data",
    "redirect_uri": "http://localhost:1027/login",
    "url": "http://localhost:1027/ngsi-ld/v1",
    "grant_type": [
      "authorization_code",
      "implicit",
      "password"
    ]
  }
}' | http  POST http://localhost:3005/v1/applications \
 Content-Type:'application/json' \
 X-Auth-Token:"$TOKEN" | jq -r .application.id)

export APP

echo -e "          ... Application ID: $APP"

#
# Create the corresponding permissions
#
echo
echo -e "⏳ Creating the permissions for /entities and /entityOperations"

printf '{
  "permission": {
    "name": "Permission to get Personal Data information of an entity (all entities)",
    "action": "GET",
    "resource": "/entities/*",
    "is_regex": true
  }
}' | http -q POST "http://localhost:3005/v1/applications/$APP/permissions" \
 Content-Type:'application/json' \
 X-Auth-Token:"$TOKEN"

for a in person001 person002 person003 person004
do
  a="urn:ngsi-ld:Person:"$a

  printf '{
  "permission": {
    "name": "Permission to get Personal Data information of an entity (%s)",
    "action": "GET",
    "resource": "/entities/%s"
  }
}' $a $a  | http -q POST "http://localhost:3005/v1/applications/$APP/permissions" \
 Content-Type:'application/json' \
 X-Auth-Token:"$TOKEN"

  printf '{
  "permission": {
    "name": "Permission to Update the Personal Data information associated to an entity (%s)",
    "action": "PATCH",
    "resource": "/entities/%s"
  }
}' $a $a  | http -q POST "http://localhost:3005/v1/applications/$APP/permissions" \
 Content-Type:'application/json' \
 X-Auth-Token:"$TOKEN"

done

printf '{
  "permission": {
    "name": "Permission to add some entities",
    "action": "POST",
    "resource": "/entityOperations/upsert",
  }
}' | http -q POST "http://localhost:3005/v1/applications/$APP/permissions" \
 Content-Type:'application/json' \
 X-Auth-Token:"$TOKEN"

printf '{
  "permission": {
    "name": "Permission to update the information associated to an entity (all entities)",
    "action": "PATCH",
    "resource": "/entities/*",
    "is_regex": true
  }
}' | http -q POST "http://localhost:3005/v1/applications/$APP/permissions" \
 Content-Type:'application/json' \
 X-Auth-Token:"$TOKEN"

echo
echo -e " \033[1;32mdone\033[0m"
