#!/bin/bash
#
#  http commands to create the organizations and assign the users
#
#

set -e

echo -e "⏳ Creating organizations into IdM"

echo -e "      Obtaining the X-Subject-Token for admin user: Alice"

#
# Get admin token
#
TOKEN=$(http -h POST http://localhost:3005/v1/auth/tokens \
  name=alice-the-admin@test.com \
  password=test | grep 'X-Subject-Token' | awk '{print $2}')

echo -e "          ... $TOKEN"

#
# Create the four organizations: Managers, Users, Data, Others
#

printf '{
  "organization": {
    "name": "Managers",
    "description": "This group is for the Project Managers of the Personal Data application with full control access"
  }
}'| http  POST http://localhost:3005/v1/organizations \
 Content-Type:'application/json' \
 X-Auth-Token:"$TOKEN"

printf '{
  "organization": {
    "name": "Users",
    "description": "This group is for the Project Users of the Personal Data application with read control access"
  }
}'| http  POST http://localhost:3005/v1/organizations \
 Content-Type:'application/json' \
 X-Auth-Token:"$TOKEN"

printf '{
  "organization": {
    "name": "Data",
    "description": "This group is for the Personal Data owners who can read and modify only their own data"
  }
}'| http  POST http://localhost:3005/v1/organizations \
 Content-Type:'application/json' \
 X-Auth-Token:"$TOKEN"

printf '{
  "organization": {
    "name": "Others",
    "description": "This group is for the rest of IdM registered users not authorized to access the Personal Data Application"
  }
}'| http  POST http://localhost:3005/v1/organizations \
 Content-Type:'application/json' \
 X-Auth-Token:"$TOKEN"
