#!/bin/bash
#
#  Command Line Interface to start all services associated with the Getting-Started Tutorial
#
#  For this tutorial the commands are merely a convenience script to run docker-compose
#

set -e
# set -x
echo

if (( $# != 1 )); then
    echo "Illegal number of parameters"
    echo "usage: services [help|create|start|stop]"
    exit 1
fi

loadData () {
	export CONTEXT_BROKER="$1"
	addDatabaseIndex

  echo -e "\n⏳ Uploading some data into the \033[1;34mOrionLD\033[0m\n"
	docker run --rm -v "$(pwd)"/import-data:/import-data \
		--network fiware_default \
		-e CONTEXT_BROKER="${CONTEXT_BROKER}" \
		-e TUTORIAL_DATA_MODELS_CONTEXT="https://schema.lab.fiware.org/ld/context" \
		--entrypoint /bin/ash curlimages/curl import-data
}

waitForKeyrock () {
	echo -e "\n⏳ Waiting for \033[1;31mIdM\033[0m to be available"

  status=$(http -h http://localhost:3005/version 2>/dev/null | grep HTTP/ | awk '{print $2}')
	while (( status != 200 ))
	do
		echo -e "IdM HTTP state: $status (waiting for 200)"
		sleep 5
    status=$(http -h http://localhost:3005/version 2>/dev/null | grep HTTP/ | awk '{print $2}')
	done

	echo -e " \033[1;32mdone\033[0m"
}

waitForOrion () {
	echo -e "\n⏳ Waiting for \033[1;34mOrionLD\033[0m to be available"

	status=$(http -h http://localhost:1026/version 2>/dev/null | grep HTTP/ | awk '{print $2}')
	while (( status != 200 ))
	do
	  echo -e "Context Broker HTTP state: $status (waiting for 200)"
	  sleep 1
	  status=$(http -h http://localhost:1026/version 2>/dev/null | grep HTTP/ | awk '{print $2}')
	done

  echo -e " \033[1;32mdone\033[0m"
}

displayServices () {
	echo ""
	docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}" --filter name=fiware-*

  echo -e " \033[1;32mdone\033[0m"
}

addDatabaseIndex () {
	echo -e "\n⏳ Adding appropriate \033[1mMongoDB\033[0m indexes for \033[1;34mOrionLD\033[0m  ..."
	docker exec  mongo-db mongo --eval '
	conn = new Mongo();db.createCollection("orion");
	db = conn.getDB("orion");
	db.createCollection("entities");
	db.entities.createIndex({"_id.servicePath": 1, "_id.id": 1, "_id.type": 1}, {unique: true});
	db.entities.createIndex({"_id.type": 1});
	db.entities.createIndex({"_id.id": 1});' > /dev/null

	docker exec  mongo-db mongo --eval '
	conn = new Mongo();db.createCollection("orion-openiot");
	db = conn.getDB("orion-openiot");
	db.createCollection("entities");
	db.entities.createIndex({"_id.servicePath": 1, "_id.id": 1, "_id.type": 1}, {unique: true});
	db.entities.createIndex({"_id.type": 1});
	db.entities.createIndex({"_id.id": 1});' > /dev/null

	echo -e " \033[1;32mdone\033[0m"
}

startContainers () {
	echo ""
	export IDM_HTTPS_ENABLED="$1"
	docker-compose --log-level ERROR -p fiware up -d --remove-orphans

  echo -e  " \033[1;32mdone\033[0m"
}

stoppingContainers () {
	echo "Stopping containers"
	docker-compose --log-level ERROR -p fiware down -v --remove-orphans

  if [ -f "docker-compose.yml.bak" ]; then
    echo -e "\n⏳ Recovering original docker-compose.yml file..."
    sed -i '' 's/^.*PEP_PASSWORD=.*$/      - PEP_PASSWORD=test/g' docker-compose.yml
    sed -i '' 's/^.*PEP_PROXY_USERNAME=.*$/      - PEP_PROXY_USERNAME=pep_proxy_00000000-0000-0000-0000-000000000000/g' docker-compose.yml
    sed -i '' 's/^.*PEP_PROXY_APP_ID=.*$/      - PEP_PROXY_APP_ID=tutorial-dckr-site-0000-xpresswebapp/g' docker-compose.yml

    rm docker-compose.yml.bak
  fi

  printf " \033[1;32mdone\033[0m\n"
}

command="$1"
case "${command}" in
	"help")
    echo "usage: services [help|create|start|stop]"
    ;;
  "start")
		stoppingContainers
		echo -e "\nStarting five containers: \033[1;34mOrionLD\033[0m, \033[1;31mIdM\033[0m, \033[1;31mOrion PEP Proxy\033[0m, and \033[1mMongoDB\033[0m and \033[1mMySQL\033[0m databases."
		echo -e "- \033[1;34mOrionLD\033[0m is the Context Broker"
		echo -e "- \033[1;31mIdM\033[0m is an Identity Management Front-End"
		echo -e "- \033[1;31mOrion PEP Proxy\033[0m is a PEP Proxy around \033[1;34mOrionLD\033[0m"
		startContainers false
		waitForKeyrock
		waitForOrion
		loadData orionld:1026
		displayServices
		;;
	"stop")
		stoppingContainers
		;;
	"create")
		echo "Pulling Docker images"
		docker-compose --log-level ERROR -p fiware pull
		;;
	*)
		echo "Command not Found."
		echo "usage: services [help|create|start|stop]"
		exit 127;
		;;
esac
