name: CI
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test-modules:
    name: Test Script
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false
        fetch-depth: 0
        submodules: recursive
    - name: Build Images
      run: |
        ./services create || true
    - name: Run Script
      run: |
        ./services start && ./services stop

  lint-markdown:
    name: Lint Markdown
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Lint changelog file
        uses: docker://avtodev/markdown-lint:v1 # fastest way
        with:
          rules: '/lint/rules/changelog.js'
          config: '/lint/config/changelog.yml'
          args: './README.md'

  lint-shell:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Run Shellcheck
        uses: azohra/shell-linter@latest
        with:
          path: "services, users-organizations, import-data, application-management"