name: Lint
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  lint-markdown:
    name: Lint readme file
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Lint changelog file
      uses: docker://avtodev/markdown-lint:v1 # fastest way
      with:
        config: '.github/workflows/.markdownlint.json'
        args: './index.md'

  lint-shell:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Run Shellcheck
        uses: azohra/shell-linter@latest
        with:
          path: "services, users-organizations, import-data, application-management"