name: Lint
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  write_good_job:
    runs-on: ubuntu-latest
    name: A job to lint Markdown files
    steps:
    - uses: actions/checkout@v2
    - name: write-good action step
      id: write-good
      uses: tomwhross/write-good-action@v1.2
    # Use the output from the `write-good` step
    - name: Get the write-good output
      run: echo "${{ steps.write-good.outputs.result }}"

  docker-example:
    runs-on: ubuntu-latest
    name: other lint job
    steps:
    - uses: actions/checkout@v2
    - name: Run box version docker run -it --rm -v "$(pwd)":/srv/app -w /srv/app btford/write-good:latest *.md
      uses: docker://btford/write-good:latest
      with:
        args: './README.md'

  lint-markdown:
    name: Lint readme file
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Lint changelog file
      uses: docker://avtodev/markdown-lint:v1 # fastest way
      with:
        config: '.github/workflows/.markdownlint.json'
        args: './README.md'

  lint-shell:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Run Shellcheck
        uses: azohra/shell-linter@latest
        with:
          path: "services, users-organizations, import-data, application-management"